LANGSMITH_TRACING=true
GROQ_API_KEY="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"
LANGSMITH_ENDPOINT="https://api.smith.langchain.com"
LANGSMITH_API_KEY="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"
LANGSMITH_PROJECT="pr-elderly-candle-25"

[database]
user = "root"
password = "gray1380"
host = "localhost"
port = "3306"
database = "sys"